# Generated by Django 3.2.5 on 2022-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.CharField(max_length=15)),
                ('form_date', models.DateField()),
                ('guardian_name', models.CharField(max_length=200)),
                ('mothers_maiden_name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('educational_qualification', models.CharField(max_length=50)),
                ('membership_fee', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('introduced_by', models.CharField(max_length=15)),
                ('witness', models.CharField(max_length=250)),
            ],
        ),
    ]
