# Generated by Django 3.2.5 on 2022-05-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='form_date',
            new_name='form_data',
        ),
    ]
