# Generated by Django 3.2.5 on 2022-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20220506_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='form_data',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='form_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='form_no',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
